platform :ios, '13.0'

target 'MediationExample' do
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'OpAdxSdk', '2.14.0'
  pod 'GMAOperaSDKAdapter', '2.14.0.0'
#
#  if ENV['BUILD_SNIPPETS']
#    pod 'Snippets', :path => './Snippets'
#  end

end
